"""Add Review Model

Revision ID: 28078149d349
Revises: bf87e5749dac
Create Date: 2023-06-29 09:33:33.678754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28078149d349'
down_revision = 'bf87e5749dac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
